### ISSUE TITLE
Is it able to detach this repo from original truthcoin-cpp ?

### ISSUE THREAD

**Issue by joemphilips** [bitcoin-hivemind/hivemind#86]
I have tried to search src of this repo but according to current Github specification, It's not possible until it becomes standalone repo.
Is it OK to detach it?

**Comment by CryptAxe** [comment]
You'd be much better off using grep and reading the hivemind docs in the
docs folder honestly.

Since we are a fork of bitcoin, and I'll be rebasing / updating the
hivemind source on top of upstream bitcoin I don't know if we should detach
the repo. Maybe we should all get together and discuss this on slack some
time soon?

On Mar 29, 2017 5:52 PM, "Joe Miyamoto" <notifications@github.com> wrote:

I have tried to search src of this repo but according to current Github
specification, It's not possible until it becomes standalone repo.
Is it OK to detach it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitcoin-hivemind/hivemind/issues/86>, or mute the thread

**Comment by joemphilips** [comment]
I got It. Thanks!

**Comment by CryptAxe** [comment]
Also, if you're trying to find something in parricular or anything is
confusing you can ask me on slack or email (add at g mail dot com to my
github name).

Here's one of the more useful files in the docs folder I mentioned:

https://github.com/bitcoin-hivemind/hivemind/blob/master/doc/notes_hivemind.txt

**Comment by joemphilips** [comment]
Thanks! I'd better take time to understand Automated Market Maker more thoroughly.
